// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemRezerwacjiHotelowej.Data;

#nullable disable

namespace SystemRezerwacjiHotelowej.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SystemRezerwacjiHotelowej.Components.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Animator")
                        .HasColumnType("bit");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<bool>("CzyOplacona")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZameldowany")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataMeldunku")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataWymeldowania")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiczbaOsob")
                        .HasColumnType("int");

                    b.Property<bool>("Parking")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SystemRezerwacjiHotelowej.Components.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenaZaDobe")
                        .HasColumnType("int");

                    b.Property<int>("IloscOsob")
                        .HasColumnType("int");

                    b.Property<int>("Numer")
                        .HasColumnType("int");

                    b.Property<int>("Pietro")
                        .HasColumnType("int");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 101,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 2,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 102,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 3,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 103,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 4,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 104,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 5,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 105,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 6,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 106,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 7,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 107,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 8,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 108,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 9,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 109,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 10,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 110,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 11,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 111,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 12,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 112,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 13,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 113,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 14,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 114,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 15,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 115,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 16,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 116,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 17,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 117,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 18,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 118,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 19,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 119,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 20,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 120,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 21,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 121,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 22,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 122,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 23,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 123,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 24,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 124,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 25,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 125,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 26,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 126,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 27,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 127,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 28,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 128,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 29,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 129,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 30,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 130,
                            Pietro = 1,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 31,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 201,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 32,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 202,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 33,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 203,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 34,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 204,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 35,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 205,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 36,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 206,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 37,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 207,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 38,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 208,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 39,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 209,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 40,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 210,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 41,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 211,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 42,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 212,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 43,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 213,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 44,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 214,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 45,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 215,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 46,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 216,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 47,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 217,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 48,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 218,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 49,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 219,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 50,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 220,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 51,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 221,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 52,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 222,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 53,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 223,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 54,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 224,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 55,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 225,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 56,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 226,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 57,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 227,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 58,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 228,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 59,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 229,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 60,
                            CenaZaDobe = 1000,
                            IloscOsob = 4,
                            Numer = 230,
                            Pietro = 2,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 61,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 301,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 62,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 302,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 63,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 303,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 64,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 304,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 65,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 305,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 66,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 306,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 67,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 307,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 68,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 308,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 69,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 309,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 70,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 310,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 71,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 311,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 72,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 312,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 73,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 313,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 74,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 314,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 75,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 315,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 76,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 316,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 77,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 317,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 78,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 318,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 79,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 319,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 80,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 320,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 81,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 321,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 82,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 322,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 83,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 323,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 84,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 324,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 85,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 325,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 86,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 326,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 87,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 327,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 88,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 328,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 89,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 329,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 90,
                            CenaZaDobe = 800,
                            IloscOsob = 3,
                            Numer = 330,
                            Pietro = 3,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 91,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 401,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 92,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 402,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 93,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 403,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 94,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 404,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 95,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 405,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 96,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 406,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 97,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 407,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 98,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 408,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 99,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 409,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 100,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 410,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 101,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 411,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 102,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 412,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 103,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 413,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 104,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 414,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 105,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 415,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 106,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 416,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 107,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 417,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 108,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 418,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 109,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 419,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 110,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 420,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 111,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 421,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 112,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 422,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 113,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 423,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 114,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 424,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 115,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 425,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 116,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 426,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 117,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 427,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 118,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 428,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 119,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 429,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 120,
                            CenaZaDobe = 500,
                            IloscOsob = 2,
                            Numer = 430,
                            Pietro = 4,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 121,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 501,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 122,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 502,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 123,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 503,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 124,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 504,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 125,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 505,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 126,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 506,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 127,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 507,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 128,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 508,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 129,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 509,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 130,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 510,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 131,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 511,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 132,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 512,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 133,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 513,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 134,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 514,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 135,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 515,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 136,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 516,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 137,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 517,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 138,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 518,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 139,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 519,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 140,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 520,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 141,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 521,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 142,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 522,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 143,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 523,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 144,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 524,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 145,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 525,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 146,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 526,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 147,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 527,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 148,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 528,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 149,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 529,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 150,
                            CenaZaDobe = 300,
                            IloscOsob = 1,
                            Numer = 530,
                            Pietro = 5,
                            Standard = "ekonomiczny"
                        },
                        new
                        {
                            Id = 151,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 601,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 152,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 602,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 153,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 603,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 154,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 604,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 155,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 605,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 156,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 606,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 157,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 607,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 158,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 608,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 159,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 609,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 160,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 610,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 161,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 611,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 162,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 612,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 163,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 613,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 164,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 614,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 165,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 615,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 166,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 616,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 167,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 617,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 168,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 618,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 169,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 619,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 170,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 620,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 171,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 621,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 172,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 622,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 173,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 623,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 174,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 624,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 175,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 625,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 176,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 626,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 177,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 627,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 178,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 628,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 179,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 629,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 180,
                            CenaZaDobe = 700,
                            IloscOsob = 2,
                            Numer = 630,
                            Pietro = 6,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 181,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 701,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 182,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 702,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 183,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 703,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 184,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 704,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 185,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 705,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 186,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 706,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 187,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 707,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 188,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 708,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 189,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 709,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 190,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 710,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 191,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 711,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 192,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 712,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 193,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 713,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 194,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 714,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 195,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 715,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 196,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 716,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 197,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 717,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 198,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 718,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 199,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 719,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 200,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 720,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 201,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 721,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 202,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 722,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 203,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 723,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 204,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 724,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 205,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 725,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 206,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 726,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 207,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 727,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 208,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 728,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 209,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 729,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 210,
                            CenaZaDobe = 400,
                            IloscOsob = 1,
                            Numer = 730,
                            Pietro = 7,
                            Standard = "superior"
                        },
                        new
                        {
                            Id = 211,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 801,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 212,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 802,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 213,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 803,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 214,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 804,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 215,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 805,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 216,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 806,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 217,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 807,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 218,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 808,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 219,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 809,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 220,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 810,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 221,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 811,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 222,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 812,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 223,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 813,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 224,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 814,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 225,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 815,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 226,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 816,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 227,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 817,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 228,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 818,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 229,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 819,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 230,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 820,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 231,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 821,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 232,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 822,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 233,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 823,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 234,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 824,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 235,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 825,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 236,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 826,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 237,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 827,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 238,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 828,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 239,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 829,
                            Pietro = 8,
                            Standard = "deluxe"
                        },
                        new
                        {
                            Id = 240,
                            CenaZaDobe = 500,
                            IloscOsob = 1,
                            Numer = 830,
                            Pietro = 8,
                            Standard = "deluxe"
                        });
                });

            modelBuilder.Entity("SystemRezerwacjiHotelowej.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SystemRezerwacjiHotelowej.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SystemRezerwacjiHotelowej.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemRezerwacjiHotelowej.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SystemRezerwacjiHotelowej.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
